import type { Opportunity } from "@/lib/types";

export const opportunities: Opportunity[] = [
  {
    id: "global-hack-lab",
    title: "Global Hack Lab Challenge",
    type: "Hackathon",
    country: "Online",
    mode: "Online",
    deadline: "2026-07-15",
    ageRange: "14-19",
    cost: "Free",
    difficulty: "Intermediate",
    relevantMajors: ["Computer Science", "Engineering", "Data Science"],
    linkPlaceholder: "https://example.com/global-hack-lab",
    whyItHelps: "Creates a time-bound project, team evidence, and demo material for the portfolio vault."
  },
  {
    id: "math-olympiad-pathway",
    title: "Math Olympiad Regional Pathway",
    type: "Olympiad",
    country: "Multiple",
    mode: "In person",
    deadline: "2026-09-01",
    ageRange: "13-18",
    cost: "Low",
    difficulty: "Competitive",
    relevantMajors: ["Mathematics", "Computer Science", "Engineering", "Economics"],
    linkPlaceholder: "https://example.com/math-olympiad",
    whyItHelps: "Adds rigorous external validation for quantitative majors."
  },
  {
    id: "youth-research-sprint",
    title: "Youth Research Sprint",
    type: "Research program",
    country: "Online",
    mode: "Online",
    deadline: "2026-08-05",
    ageRange: "15-19",
    cost: "Medium",
    difficulty: "Intermediate",
    relevantMajors: ["Biology", "Computer Science", "Psychology", "Economics"],
    linkPlaceholder: "https://example.com/research-sprint",
    whyItHelps: "Turns curiosity into a mentored question, literature review, and written output."
  },
  {
    id: "summer-stem-institute",
    title: "Summer STEM Institute",
    type: "Summer school",
    country: "United States",
    mode: "Hybrid",
    deadline: "2026-02-20",
    ageRange: "15-18",
    cost: "High",
    difficulty: "Competitive",
    relevantMajors: ["Engineering", "Computer Science", "Physics"],
    linkPlaceholder: "https://example.com/summer-stem",
    whyItHelps: "Builds advanced academic exposure and a structured project artifact."
  },
  {
    id: "local-civic-data-internship",
    title: "Civic Data Internship",
    type: "Internship",
    country: "Online",
    mode: "Hybrid",
    deadline: "2026-06-30",
    ageRange: "16-20",
    cost: "Free",
    difficulty: "Intermediate",
    relevantMajors: ["Data Science", "Public Policy", "Economics", "Computer Science"],
    linkPlaceholder: "https://example.com/civic-data",
    whyItHelps: "Connects technical skills to measurable community impact."
  },
  {
    id: "global-scholarship-builder",
    title: "Global Scholarship Builder",
    type: "Scholarship",
    country: "Multiple",
    mode: "Online",
    deadline: "2026-10-10",
    ageRange: "16-20",
    cost: "Free",
    difficulty: "Competitive",
    relevantMajors: ["All majors"],
    linkPlaceholder: "https://example.com/scholarship-builder",
    whyItHelps: "Creates funding research habits and an early evidence list for applications."
  },
  {
    id: "community-tech-helpdesk",
    title: "Community Tech Helpdesk",
    type: "Volunteering",
    country: "Local",
    mode: "In person",
    deadline: "2026-12-31",
    ageRange: "14-20",
    cost: "Free",
    difficulty: "Introductory",
    relevantMajors: ["Computer Science", "Education", "Business", "Public Policy"],
    linkPlaceholder: "https://example.com/community-tech",
    whyItHelps: "Turns service into measurable outcomes, testimonials, and leadership proof."
  },
  {
    id: "machine-learning-foundations",
    title: "Machine Learning Foundations Studio",
    type: "Online course",
    country: "Online",
    mode: "Online",
    deadline: "2026-11-01",
    ageRange: "14-20",
    cost: "Low",
    difficulty: "Intermediate",
    relevantMajors: ["Computer Science", "Data Science", "Engineering"],
    linkPlaceholder: "https://example.com/ml-foundations",
    whyItHelps: "Provides structured skills that can feed a real portfolio project."
  },
  {
    id: "future-essayist-prize",
    title: "Future Essayist Prize",
    type: "Writing competition",
    country: "United Kingdom",
    mode: "Online",
    deadline: "2026-06-12",
    ageRange: "15-19",
    cost: "Free",
    difficulty: "Competitive",
    relevantMajors: ["Law", "Economics", "Humanities", "Public Policy"],
    linkPlaceholder: "https://example.com/future-essayist",
    whyItHelps: "Builds argumentative writing proof and a thoughtful academic artifact."
  },
  {
    id: "bio-design-challenge",
    title: "Bio Design Challenge",
    type: "Hackathon",
    country: "Singapore",
    mode: "Hybrid",
    deadline: "2026-08-18",
    ageRange: "15-19",
    cost: "Low",
    difficulty: "Intermediate",
    relevantMajors: ["Biology", "Medicine", "Engineering"],
    linkPlaceholder: "https://example.com/bio-design",
    whyItHelps: "Combines scientific inquiry with prototype evidence and user feedback."
  },
  {
    id: "robotics-open-build",
    title: "Robotics Open Build League",
    type: "Olympiad",
    country: "Multiple",
    mode: "In person",
    deadline: "2026-09-20",
    ageRange: "13-18",
    cost: "Medium",
    difficulty: "Competitive",
    relevantMajors: ["Engineering", "Computer Science", "Physics"],
    linkPlaceholder: "https://example.com/robotics-open",
    whyItHelps: "Shows iteration, team roles, engineering documentation, and competition proof."
  },
  {
    id: "youth-public-health-map",
    title: "Youth Public Health Mapping Project",
    type: "Research program",
    country: "Online",
    mode: "Online",
    deadline: "2026-07-01",
    ageRange: "15-20",
    cost: "Free",
    difficulty: "Intermediate",
    relevantMajors: ["Medicine", "Public Health", "Data Science", "Biology"],
    linkPlaceholder: "https://example.com/health-map",
    whyItHelps: "Connects research, data, and service with a clear public-facing artifact."
  }
];
