import type { ApplicationSystem, CostLevel, Selectivity, TestingExpectation, University } from "@/lib/types";

const dataNote = "Editable sample data. Verify official requirements and deadlines before making decisions.";

const baseUniversities: University[] = [
  {
    id: "mit",
    name: "MIT",
    country: "United States",
    region: "US",
    strongMajors: ["Computer Science", "Engineering", "Physics", "Economics"],
    selectivity: "Highly selective",
    academicExpectations: "Very strong math, science, and sustained academic rigor are typically important.",
    testingExpectations: "Required",
    portfolioExpectations: "Evidence of technical depth, problem solving, projects, research, or competitions can strengthen fit.",
    suggestedStudentProfile: "Builder with advanced coursework, rigorous problem solving, and proof of technical initiative.",
    deadlinesPlaceholder: "Sample: early November and early January windows. Verify official MIT dates.",
    costLevel: "High",
    applicationSystem: "Direct",
    programs: [{ name: "Electrical Engineering and Computer Science", sampleExpectations: "Advanced math and maker proof." }],
    dataNote
  },
  {
    id: "stanford",
    name: "Stanford University",
    country: "United States",
    region: "US",
    strongMajors: ["Computer Science", "Entrepreneurship", "Engineering", "Humanities"],
    selectivity: "Highly selective",
    academicExpectations: "High academic performance with challenging courses and intellectual curiosity.",
    testingExpectations: "Optional",
    portfolioExpectations: "Clear initiative, leadership, project ownership, and authentic impact matter.",
    suggestedStudentProfile: "Self-directed student with unusual initiative and strong narrative fit.",
    deadlinesPlaceholder: "Sample: early November and early January windows. Verify official Stanford dates.",
    costLevel: "High",
    applicationSystem: "Common App",
    programs: [{ name: "Symbolic Systems", sampleExpectations: "Interdisciplinary proof across computation and society." }],
    dataNote
  },
  {
    id: "harvard",
    name: "Harvard University",
    country: "United States",
    region: "US",
    strongMajors: ["Economics", "Government", "Biology", "Computer Science"],
    selectivity: "Highly selective",
    academicExpectations: "Exceptional academic preparation across a rigorous curriculum.",
    testingExpectations: "Required",
    portfolioExpectations: "Proof of leadership, depth, service, and intellectual contribution can help readiness.",
    suggestedStudentProfile: "High-achieving student with sustained excellence and meaningful community contribution.",
    deadlinesPlaceholder: "Sample: early November and early January windows. Verify official Harvard dates.",
    costLevel: "High",
    applicationSystem: "Common App",
    programs: [{ name: "Economics", sampleExpectations: "Quantitative strength and real-world inquiry." }],
    dataNote
  },
  {
    id: "uc-berkeley",
    name: "UC Berkeley",
    country: "United States",
    region: "US",
    strongMajors: ["Computer Science", "Engineering", "Data Science", "Business"],
    selectivity: "Highly selective",
    academicExpectations: "Strong grades in rigorous courses, especially for impacted majors.",
    testingExpectations: "Optional",
    portfolioExpectations: "Impactful projects, academic initiative, and clear major fit are useful proof points.",
    suggestedStudentProfile: "Academically strong student with a specific intellectual direction and public evidence.",
    deadlinesPlaceholder: "Sample: UC application window in fall. Verify official UC dates.",
    costLevel: "High",
    applicationSystem: "UC Application",
    programs: [{ name: "Electrical Engineering and Computer Sciences", sampleExpectations: "Math rigor and project proof." }],
    dataNote
  },
  {
    id: "carnegie-mellon",
    name: "Carnegie Mellon University",
    country: "United States",
    region: "US",
    strongMajors: ["Computer Science", "Robotics", "Design", "Drama"],
    selectivity: "Highly selective",
    academicExpectations: "Advanced coursework and strong quantitative preparation are helpful for technical schools.",
    testingExpectations: "Optional",
    portfolioExpectations: "Technical demos, repositories, design process, or research evidence can be valuable.",
    suggestedStudentProfile: "Deep specialist with tangible artifacts and evidence of craft.",
    deadlinesPlaceholder: "Sample: fall and winter application windows. Verify official CMU dates.",
    costLevel: "High",
    applicationSystem: "Common App",
    programs: [{ name: "School of Computer Science", sampleExpectations: "Depth in CS, math, and original building." }],
    dataNote
  },
  {
    id: "oxford",
    name: "University of Oxford",
    country: "United Kingdom",
    region: "UK",
    strongMajors: ["Law", "Medicine", "Computer Science", "PPE"],
    selectivity: "Highly selective",
    academicExpectations: "Excellent subject-specific preparation and strong performance in relevant qualifications.",
    testingExpectations: "Situational",
    portfolioExpectations: "Subject mastery, reading, super-curricular work, and interview preparation are central.",
    suggestedStudentProfile: "Academically focused student with deep subject fluency and strong written reasoning.",
    deadlinesPlaceholder: "Sample: October UCAS deadline for many Oxford courses. Verify official course dates.",
    costLevel: "High",
    applicationSystem: "UCAS",
    programs: [{ name: "Computer Science", sampleExpectations: "Math aptitude, assessment preparation, deep CS interest." }],
    dataNote
  },
  {
    id: "cambridge",
    name: "University of Cambridge",
    country: "United Kingdom",
    region: "UK",
    strongMajors: ["Natural Sciences", "Engineering", "Mathematics", "Economics"],
    selectivity: "Highly selective",
    academicExpectations: "Exceptional subject preparation and strong academic trajectory.",
    testingExpectations: "Situational",
    portfolioExpectations: "Super-curricular depth, relevant reading, problem solving, and interview readiness matter.",
    suggestedStudentProfile: "Student with intense subject focus and evidence of advanced academic thinking.",
    deadlinesPlaceholder: "Sample: October UCAS deadline for many Cambridge courses. Verify official course dates.",
    costLevel: "High",
    applicationSystem: "UCAS",
    programs: [{ name: "Engineering", sampleExpectations: "Math and physics strength plus design thinking." }],
    dataNote
  },
  {
    id: "imperial",
    name: "Imperial College London",
    country: "United Kingdom",
    region: "UK",
    strongMajors: ["Engineering", "Computing", "Medicine", "Natural Sciences"],
    selectivity: "Highly selective",
    academicExpectations: "Strong STEM grades and advanced subject preparation.",
    testingExpectations: "Situational",
    portfolioExpectations: "STEM projects, competitions, research reading, and technical proof support readiness.",
    suggestedStudentProfile: "STEM-focused student with rigorous academics and clear technical motivation.",
    deadlinesPlaceholder: "Sample: UCAS course-specific dates. Verify official Imperial dates.",
    costLevel: "High",
    applicationSystem: "UCAS",
    programs: [{ name: "Computing", sampleExpectations: "Math depth and computational project proof." }],
    dataNote
  },
  {
    id: "ucl",
    name: "UCL",
    country: "United Kingdom",
    region: "UK",
    strongMajors: ["Architecture", "Economics", "Psychology", "Computer Science"],
    selectivity: "Highly selective",
    academicExpectations: "Strong subject grades and a convincing course-specific statement.",
    testingExpectations: "Situational",
    portfolioExpectations: "Course-aligned proof, especially for creative, built environment, and technical subjects.",
    suggestedStudentProfile: "Student with strong academic fit and well-documented course motivation.",
    deadlinesPlaceholder: "Sample: UCAS dates vary by course. Verify official UCL dates.",
    costLevel: "High",
    applicationSystem: "UCAS",
    programs: [{ name: "Information Management for Business", sampleExpectations: "Technology, business, and impact proof." }],
    dataNote
  },
  {
    id: "toronto",
    name: "University of Toronto",
    country: "Canada",
    region: "Canada",
    strongMajors: ["Computer Science", "Engineering", "Life Sciences", "Commerce"],
    selectivity: "Selective",
    academicExpectations: "Strong grades in required subjects and consistent academic performance.",
    testingExpectations: "Situational",
    portfolioExpectations: "Projects, community contribution, and subject-aligned activities can clarify readiness.",
    suggestedStudentProfile: "Academically strong student with clear program fit and consistent evidence.",
    deadlinesPlaceholder: "Sample: winter application windows vary by program. Verify official U of T dates.",
    costLevel: "High",
    applicationSystem: "OUAC",
    programs: [{ name: "Computer Science", sampleExpectations: "Math preparation and computing initiative." }],
    dataNote
  },
  {
    id: "waterloo",
    name: "University of Waterloo",
    country: "Canada",
    region: "Canada",
    strongMajors: ["Computer Science", "Engineering", "Mathematics", "Co-op"],
    selectivity: "Highly selective",
    academicExpectations: "Strong math grades and prerequisite preparation are important for competitive programs.",
    testingExpectations: "Situational",
    portfolioExpectations: "Programming, contest results, work experience, and measurable technical work can help.",
    suggestedStudentProfile: "Technical student with math strength, initiative, and practical build evidence.",
    deadlinesPlaceholder: "Sample: winter program deadlines. Verify official Waterloo dates.",
    costLevel: "High",
    applicationSystem: "OUAC",
    programs: [{ name: "Software Engineering", sampleExpectations: "High math readiness and sustained coding evidence." }],
    dataNote
  },
  {
    id: "mcgill",
    name: "McGill University",
    country: "Canada",
    region: "Canada",
    strongMajors: ["Life Sciences", "Engineering", "Arts", "Management"],
    selectivity: "Selective",
    academicExpectations: "Strong grades aligned to faculty requirements.",
    testingExpectations: "Situational",
    portfolioExpectations: "Academic consistency and subject-aligned experience can support profile strength.",
    suggestedStudentProfile: "Student with strong coursework and clear faculty fit.",
    deadlinesPlaceholder: "Sample: winter application deadlines. Verify official McGill dates.",
    costLevel: "Medium",
    applicationSystem: "Direct",
    programs: [{ name: "Bioengineering", sampleExpectations: "STEM rigor and health or engineering exploration." }],
    dataNote
  },
  {
    id: "nus",
    name: "National University of Singapore",
    country: "Singapore",
    region: "Singapore",
    strongMajors: ["Computer Science", "Engineering", "Business", "Medicine"],
    selectivity: "Highly selective",
    academicExpectations: "High academic performance in recognized curricula and strong subject prerequisites.",
    testingExpectations: "Situational",
    portfolioExpectations: "Competitions, projects, leadership, and community evidence can strengthen fit.",
    suggestedStudentProfile: "High-performing student with regional or global evidence of initiative.",
    deadlinesPlaceholder: "Sample: spring application periods vary by qualification. Verify official NUS dates.",
    costLevel: "Medium",
    applicationSystem: "Direct",
    programs: [{ name: "Computer Science", sampleExpectations: "Math strength, coding projects, and contest readiness." }],
    dataNote
  },
  {
    id: "ntu-singapore",
    name: "NTU Singapore",
    country: "Singapore",
    region: "Singapore",
    strongMajors: ["Engineering", "Computer Science", "Business", "Communication"],
    selectivity: "Selective",
    academicExpectations: "Strong academic preparation and relevant prerequisites.",
    testingExpectations: "Situational",
    portfolioExpectations: "Engineering projects, leadership, and proof of applied learning are useful.",
    suggestedStudentProfile: "Applied builder with strong academics and hands-on technical evidence.",
    deadlinesPlaceholder: "Sample: spring application periods vary by qualification. Verify official NTU dates.",
    costLevel: "Medium",
    applicationSystem: "Direct",
    programs: [{ name: "Data Science and Artificial Intelligence", sampleExpectations: "Math, coding, and data project proof." }],
    dataNote
  },
  {
    id: "hku",
    name: "The University of Hong Kong",
    country: "Hong Kong",
    region: "Hong Kong",
    strongMajors: ["Medicine", "Law", "Business", "Engineering"],
    selectivity: "Highly selective",
    academicExpectations: "Strong grades and program-specific prerequisites.",
    testingExpectations: "Situational",
    portfolioExpectations: "Leadership, service, academic competitions, and subject exploration can help readiness.",
    suggestedStudentProfile: "Strong student with international outlook and evidence of discipline-specific interest.",
    deadlinesPlaceholder: "Sample: main round in late fall. Verify official HKU dates.",
    costLevel: "Medium",
    applicationSystem: "Direct",
    programs: [{ name: "Engineering", sampleExpectations: "Math/science rigor and applied project evidence." }],
    dataNote
  },
  {
    id: "hkust",
    name: "HKUST",
    country: "Hong Kong",
    region: "Hong Kong",
    strongMajors: ["Engineering", "Business", "Computer Science", "Science"],
    selectivity: "Selective",
    academicExpectations: "Strong STEM or business preparation, depending on program.",
    testingExpectations: "Situational",
    portfolioExpectations: "Technical proof, competitions, entrepreneurship, and research exploration are helpful.",
    suggestedStudentProfile: "STEM or business student with applied initiative and global mindset.",
    deadlinesPlaceholder: "Sample: fall and winter rounds. Verify official HKUST dates.",
    costLevel: "Medium",
    applicationSystem: "Direct",
    programs: [{ name: "Computer Science and Engineering", sampleExpectations: "Coding proof and math readiness." }],
    dataNote
  },
  {
    id: "eth-zurich",
    name: "ETH Zurich",
    country: "Switzerland",
    region: "Europe",
    strongMajors: ["Engineering", "Computer Science", "Mathematics", "Architecture"],
    selectivity: "Highly selective",
    academicExpectations: "Strong preparation in math and sciences; requirements vary by credential.",
    testingExpectations: "Situational",
    portfolioExpectations: "Technical depth, research mindset, and rigorous academic proof support readiness.",
    suggestedStudentProfile: "STEM student with exceptional math foundations and independent technical work.",
    deadlinesPlaceholder: "Sample: application windows vary by qualification. Verify official ETH Zurich dates.",
    costLevel: "Lower",
    applicationSystem: "Direct",
    programs: [{ name: "Computer Science", sampleExpectations: "Strong math and algorithmic preparation." }],
    dataNote
  },
  {
    id: "epfl",
    name: "EPFL",
    country: "Switzerland",
    region: "Europe",
    strongMajors: ["Engineering", "Computer Science", "Life Sciences", "Architecture"],
    selectivity: "Selective",
    academicExpectations: "Strong scientific and mathematical preparation.",
    testingExpectations: "Situational",
    portfolioExpectations: "STEM projects, research curiosity, and documented technical learning can help.",
    suggestedStudentProfile: "STEM-focused student with applied work and strong foundational academics.",
    deadlinesPlaceholder: "Sample: application windows vary by credential. Verify official EPFL dates.",
    costLevel: "Lower",
    applicationSystem: "Direct",
    programs: [{ name: "Life Sciences Engineering", sampleExpectations: "Biology, math, and engineering exploration." }],
    dataNote
  },
  {
    id: "yale",
    name: "Yale University",
    country: "United States",
    region: "US",
    strongMajors: ["Humanities", "Political Science", "Economics", "Biology"],
    selectivity: "Highly selective",
    academicExpectations: "Very strong academic performance across rigorous courses.",
    testingExpectations: "Required",
    portfolioExpectations: "Intellectual vitality, leadership, arts or service proof, and strong narrative fit matter.",
    suggestedStudentProfile: "Student with excellent academics, distinctive voice, and sustained contribution.",
    deadlinesPlaceholder: "Sample: early November and early January windows. Verify official Yale dates.",
    costLevel: "High",
    applicationSystem: "Common App",
    programs: [{ name: "Ethics, Politics, and Economics", sampleExpectations: "Writing, debate, public policy, and service proof." }],
    dataNote
  },
  {
    id: "princeton",
    name: "Princeton University",
    country: "United States",
    region: "US",
    strongMajors: ["Public Policy", "Engineering", "Economics", "Mathematics"],
    selectivity: "Highly selective",
    academicExpectations: "Exceptional academic strength and evidence of independent thinking.",
    testingExpectations: "Required",
    portfolioExpectations: "Research, writing, leadership, and project evidence can demonstrate readiness.",
    suggestedStudentProfile: "Academically intense student with intellectual independence and meaningful proof.",
    deadlinesPlaceholder: "Sample: early November and early January windows. Verify official Princeton dates.",
    costLevel: "High",
    applicationSystem: "Common App",
    programs: [{ name: "Operations Research and Financial Engineering", sampleExpectations: "Math rigor and applied analytics proof." }],
    dataNote
  }
];

type AdditionalUniversity = {
  id: string;
  name: string;
  country: string;
  region: string;
  logoDomain: string;
  strongMajors: string[];
  selectivity: Selectivity;
  testingExpectations: TestingExpectation;
  costLevel: CostLevel;
  applicationSystem: ApplicationSystem;
};

function createUniversity({
  id,
  name,
  country,
  region,
  logoDomain,
  strongMajors,
  selectivity,
  testingExpectations,
  costLevel,
  applicationSystem
}: AdditionalUniversity): University {
  const topMajors = strongMajors.slice(0, 3).join(", ");
  return {
    id,
    name,
    country,
    region,
    logoDomain,
    strongMajors,
    selectivity,
    academicExpectations: `Strong preparation in relevant subjects for ${topMajors}. Requirements vary by program and credential.`,
    testingExpectations,
    portfolioExpectations: "Major-aligned projects, leadership, awards, research, service, or proof artifacts can strengthen readiness when relevant.",
    suggestedStudentProfile: `Student with rigorous academics, authentic ${strongMajors[0]} interest, measurable impact, and verifiable proof.`,
    deadlinesPlaceholder: `Sample planning placeholder for ${name}. Verify official program deadlines directly.`,
    costLevel,
    applicationSystem,
    programs: [
      {
        name: strongMajors[0],
        sampleExpectations: "Subject rigor, clear motivation, and proof of sustained exploration."
      }
    ],
    dataNote
  };
}

const additionalUniversityInputs: AdditionalUniversity[] = [
  { id: "caltech", name: "Caltech", country: "United States", region: "US", logoDomain: "caltech.edu", strongMajors: ["Engineering", "Physics", "Computer Science", "Mathematics"], selectivity: "Highly selective", testingExpectations: "Required", costLevel: "High", applicationSystem: "Common App" },
  { id: "columbia", name: "Columbia University", country: "United States", region: "US", logoDomain: "columbia.edu", strongMajors: ["Engineering", "Economics", "Political Science", "Data Science"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "upenn", name: "University of Pennsylvania", country: "United States", region: "US", logoDomain: "upenn.edu", strongMajors: ["Business", "Economics", "Engineering", "Life Sciences"], selectivity: "Highly selective", testingExpectations: "Required", costLevel: "High", applicationSystem: "Common App" },
  { id: "cornell", name: "Cornell University", country: "United States", region: "US", logoDomain: "cornell.edu", strongMajors: ["Engineering", "Hotel Administration", "Computer Science", "Agriculture"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "brown", name: "Brown University", country: "United States", region: "US", logoDomain: "brown.edu", strongMajors: ["Liberal Arts", "Computer Science", "Biology", "Public Health"], selectivity: "Highly selective", testingExpectations: "Required", costLevel: "High", applicationSystem: "Common App" },
  { id: "duke", name: "Duke University", country: "United States", region: "US", logoDomain: "duke.edu", strongMajors: ["Public Policy", "Biomedical Engineering", "Economics", "Computer Science"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "uchicago", name: "University of Chicago", country: "United States", region: "US", logoDomain: "uchicago.edu", strongMajors: ["Economics", "Mathematics", "Public Policy", "Humanities"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "northwestern", name: "Northwestern University", country: "United States", region: "US", logoDomain: "northwestern.edu", strongMajors: ["Journalism", "Engineering", "Economics", "Communication"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "ucla", name: "UCLA", country: "United States", region: "US", logoDomain: "ucla.edu", strongMajors: ["Film", "Computer Science", "Biology", "Economics"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "UC Application" },
  { id: "georgia-tech", name: "Georgia Tech", country: "United States", region: "US", logoDomain: "gatech.edu", strongMajors: ["Engineering", "Computer Science", "Robotics", "Data Science"], selectivity: "Highly selective", testingExpectations: "Required", costLevel: "Medium", applicationSystem: "Common App" },
  { id: "uiuc", name: "UIUC", country: "United States", region: "US", logoDomain: "illinois.edu", strongMajors: ["Computer Science", "Engineering", "Physics", "Business"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "umich", name: "University of Michigan", country: "United States", region: "US", logoDomain: "umich.edu", strongMajors: ["Engineering", "Business", "Computer Science", "Public Policy"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "nyu", name: "NYU", country: "United States", region: "US", logoDomain: "nyu.edu", strongMajors: ["Business", "Film", "Data Science", "Economics"], selectivity: "Selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "johns-hopkins", name: "Johns Hopkins University", country: "United States", region: "US", logoDomain: "jhu.edu", strongMajors: ["Biomedical Engineering", "Public Health", "International Relations", "Neuroscience"], selectivity: "Highly selective", testingExpectations: "Required", costLevel: "High", applicationSystem: "Common App" },
  { id: "rice", name: "Rice University", country: "United States", region: "US", logoDomain: "rice.edu", strongMajors: ["Engineering", "Architecture", "Computer Science", "Music"], selectivity: "Highly selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "usc", name: "USC", country: "United States", region: "US", logoDomain: "usc.edu", strongMajors: ["Film", "Business", "Engineering", "Communication"], selectivity: "Selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "ut-austin", name: "UT Austin", country: "United States", region: "US", logoDomain: "utexas.edu", strongMajors: ["Computer Science", "Engineering", "Business", "Communications"], selectivity: "Selective", testingExpectations: "Required", costLevel: "Medium", applicationSystem: "Common App" },
  { id: "washington", name: "University of Washington", country: "United States", region: "US", logoDomain: "washington.edu", strongMajors: ["Computer Science", "Engineering", "Public Health", "Data Science"], selectivity: "Selective", testingExpectations: "Optional", costLevel: "High", applicationSystem: "Common App" },
  { id: "purdue", name: "Purdue University", country: "United States", region: "US", logoDomain: "purdue.edu", strongMajors: ["Engineering", "Aerospace", "Computer Science", "Technology"], selectivity: "Selective", testingExpectations: "Recommended", costLevel: "Medium", applicationSystem: "Common App" },
  { id: "lse", name: "London School of Economics", country: "United Kingdom", region: "UK", logoDomain: "lse.ac.uk", strongMajors: ["Economics", "Law", "Politics", "Data Science"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "UCAS" },
  { id: "kings", name: "King's College London", country: "United Kingdom", region: "UK", logoDomain: "kcl.ac.uk", strongMajors: ["Medicine", "Law", "International Relations", "Computer Science"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "UCAS" },
  { id: "edinburgh", name: "University of Edinburgh", country: "United Kingdom", region: "UK", logoDomain: "ed.ac.uk", strongMajors: ["Informatics", "Medicine", "Philosophy", "Engineering"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "UCAS" },
  { id: "manchester", name: "University of Manchester", country: "United Kingdom", region: "UK", logoDomain: "manchester.ac.uk", strongMajors: ["Engineering", "Computer Science", "Business", "Life Sciences"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "UCAS" },
  { id: "warwick", name: "University of Warwick", country: "United Kingdom", region: "UK", logoDomain: "warwick.ac.uk", strongMajors: ["Mathematics", "Economics", "Business", "Computer Science"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "UCAS" },
  { id: "bristol", name: "University of Bristol", country: "United Kingdom", region: "UK", logoDomain: "bristol.ac.uk", strongMajors: ["Engineering", "Law", "Medicine", "Economics"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "UCAS" },
  { id: "ubc", name: "University of British Columbia", country: "Canada", region: "Canada", logoDomain: "ubc.ca", strongMajors: ["Computer Science", "Commerce", "Engineering", "Life Sciences"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "Direct" },
  { id: "queens", name: "Queen's University", country: "Canada", region: "Canada", logoDomain: "queensu.ca", strongMajors: ["Commerce", "Engineering", "Political Studies", "Health Sciences"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "OUAC" },
  { id: "western", name: "Western University", country: "Canada", region: "Canada", logoDomain: "uwo.ca", strongMajors: ["Business", "Health Sciences", "Engineering", "Economics"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "OUAC" },
  { id: "alberta", name: "University of Alberta", country: "Canada", region: "Canada", logoDomain: "ualberta.ca", strongMajors: ["Engineering", "Computer Science", "Energy", "Life Sciences"], selectivity: "Moderate", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "montreal", name: "Universite de Montreal", country: "Canada", region: "Canada", logoDomain: "umontreal.ca", strongMajors: ["Medicine", "Computer Science", "Public Health", "Arts"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "smu", name: "Singapore Management University", country: "Singapore", region: "Singapore", logoDomain: "smu.edu.sg", strongMajors: ["Business", "Economics", "Information Systems", "Law"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "sutd", name: "Singapore University of Technology and Design", country: "Singapore", region: "Singapore", logoDomain: "sutd.edu.sg", strongMajors: ["Design", "Engineering", "Computer Science", "Architecture"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "cuhk", name: "Chinese University of Hong Kong", country: "Hong Kong", region: "Hong Kong", logoDomain: "cuhk.edu.hk", strongMajors: ["Medicine", "Business", "Engineering", "Data Science"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "cityu-hk", name: "City University of Hong Kong", country: "Hong Kong", region: "Hong Kong", logoDomain: "cityu.edu.hk", strongMajors: ["Engineering", "Business", "Data Science", "Media"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "polyu", name: "Hong Kong Polytechnic University", country: "Hong Kong", region: "Hong Kong", logoDomain: "polyu.edu.hk", strongMajors: ["Design", "Engineering", "Hospitality", "Health Sciences"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "tum", name: "Technical University of Munich", country: "Germany", region: "Europe", logoDomain: "tum.de", strongMajors: ["Engineering", "Computer Science", "Management", "Natural Sciences"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "lmu", name: "LMU Munich", country: "Germany", region: "Europe", logoDomain: "lmu.de", strongMajors: ["Medicine", "Humanities", "Economics", "Natural Sciences"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "tu-delft", name: "TU Delft", country: "Netherlands", region: "Europe", logoDomain: "tudelft.nl", strongMajors: ["Engineering", "Architecture", "Aerospace", "Computer Science"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "uva-amsterdam", name: "University of Amsterdam", country: "Netherlands", region: "Europe", logoDomain: "uva.nl", strongMajors: ["Social Sciences", "Data Science", "Economics", "Psychology"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "bocconi", name: "Bocconi University", country: "Italy", region: "Europe", logoDomain: "unibocconi.eu", strongMajors: ["Business", "Economics", "Finance", "Data Science"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "Direct" },
  { id: "sciences-po", name: "Sciences Po", country: "France", region: "Europe", logoDomain: "sciencespo.fr", strongMajors: ["Political Science", "Law", "Economics", "International Relations"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "ecole-polytechnique", name: "Ecole Polytechnique", country: "France", region: "Europe", logoDomain: "polytechnique.edu", strongMajors: ["Engineering", "Mathematics", "Computer Science", "Physics"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "Medium", applicationSystem: "Direct" },
  { id: "ku-leuven", name: "KU Leuven", country: "Belgium", region: "Europe", logoDomain: "kuleuven.be", strongMajors: ["Engineering", "Life Sciences", "Business", "Computer Science"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "kth", name: "KTH Royal Institute of Technology", country: "Sweden", region: "Europe", logoDomain: "kth.se", strongMajors: ["Engineering", "Computer Science", "Architecture", "Sustainability"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "karolinska", name: "Karolinska Institute", country: "Sweden", region: "Europe", logoDomain: "ki.se", strongMajors: ["Medicine", "Biomedicine", "Public Health", "Neuroscience"], selectivity: "Highly selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "copenhagen", name: "University of Copenhagen", country: "Denmark", region: "Europe", logoDomain: "ku.dk", strongMajors: ["Life Sciences", "Economics", "Computer Science", "Humanities"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "lund", name: "Lund University", country: "Sweden", region: "Europe", logoDomain: "lu.se", strongMajors: ["Engineering", "Economics", "Sustainability", "Life Sciences"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "Lower", applicationSystem: "Direct" },
  { id: "ie-university", name: "IE University", country: "Spain", region: "Europe", logoDomain: "ie.edu", strongMajors: ["Business", "Architecture", "International Relations", "Data"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "Direct" },
  { id: "esade", name: "ESADE", country: "Spain", region: "Europe", logoDomain: "esade.edu", strongMajors: ["Business", "Law", "Economics", "Innovation"], selectivity: "Selective", testingExpectations: "Situational", costLevel: "High", applicationSystem: "Direct" }
];

const additionalUniversities: University[] = additionalUniversityInputs.map(createUniversity);

export const universities: University[] = [...baseUniversities, ...additionalUniversities];

export const universityCountries = Array.from(new Set(universities.map((university) => university.country)));
